# Generated by Django 4.2.5 on 2025-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
